---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
#read the data
activity_data <- read.csv("activity.csv")

head(activity_data)

names(activity_data)
activity_data$date <- as.Date(activity_data$date, "%Y-%m-%d")
```

## What is mean total number of steps taken per day?
```{r}
#Get the Steps per day
steps_per_day <- aggregate(steps ~ date, activity_data,sum,na.rm = TRUE)

#Create Graph
hist(steps_per_day$steps,main="Steps per Day",xlab="Day",col="hotpink")

#Get the mean
mean(steps_per_day$steps)

#Get the median
median(steps_per_day$steps)

```

## What is the average daily activity pattern?
```{r}
#Average Daily Activity Pattern
time_series <- tapply(activity_data$steps, activity_data$interval, mean, na.rm = TRUE)

#Plot requested time series
plot(row.names(time_series), time_series, type = "l", xlab = "5 Minute Interval", 
     ylab = "Average Across All Days", main = "Average Number of Steps", 
     col = "blue")

#max 5 minute time interval
max_num <- which.max(time_series)
max_num
names(max_num)
```


## Imputing missing values
```{r}
#Get the missing values
missing_values <- sum(is.na(activity_data))
missing_values

#Give missing values a value
average_steps <- aggregate(steps ~ interval, data = activity_data, FUN = mean)
NA_value <- numeric()
for (i in 1:nrow(activity_data)) {
  new_data <- activity_data[i, ]
  if (is.na(new_data$steps)) {
    the_steps <- subset(average_steps, interval == new_data$interval)$steps
  } else {
    the_steps <- new_data$steps
  }
  NA_value <- c(NA_value, the_steps)
}
#Create new dataset with no missing values
upd_activity <- activity_data
upd_activity$steps <- NA_value

#upd_activity

#Make a histogram w/updated data
new_step_total <- aggregate(steps ~ date, data = upd_activity, sum, na.rm = TRUE)

hist(steps_per_day$steps,main="Steps per Day",xlab="Day",col="purple")

#Get the Mean and Median
mean(new_step_total$steps)
median(new_step_total$steps)
```
## Are there differences in activity patterns between weekdays and weekends?

```{r}
library("lattice")
get_days <- weekdays(activity_data$date)
days <- vector()
for (i in 1:nrow(activity_data)) {
  if (get_days[i] == "Saturday") {
    days[i] <- "Weekend"
  } else if (get_days[i] == "Sunday") {
    days[i] <- "Weekend"
  } else {
    days[i] <- "Weekday"
  }
}
activity_data$days <- days
activity_data$days <- factor(activity_data$days)

stepsByDay <- aggregate(steps ~ interval + days, data = activity_data, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")

xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), 
       xlab = "Interval", ylab = "Number of steps")

```



## Are there differences in activity patterns between weekdays and weekends?
